name: flutter_training
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0
  flutter: ^3.41.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training-template.git
      ref: main
      path: packages/yumemi_weather
  json_annotation: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: ^4.3.0
  build_runner: ^2.12.2
  json_serializable: ^6.13.0

flutter:
  uses-material-design: true
  assets:
    - images/